apply from: 'gradle/scripts/helpers.gradle'

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    exclusiveContent {
        forRepository {
            maven {
                name 'CurseMaven'
                url 'https://cursemaven.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'Modrinth'
                url 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
    mavenLocal() // Must be last for caching to work
}

configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
    runtimeOnly 'com.cleanroommc:osxnarratorblocker:1.0'
    runtimeOnly 'curse.maven:mmce-817377:6945422'
    runtimeOnly 'curse.maven:baubles-227083:2518667'

    implementation rfg.deobf("curse.maven:AE2FluidCraftReworkUnofficial-1404390:7742544")
    implementation rfg.deobf("curse.maven:ae2-extended-life-570458:6302098")
    compileOnly rfg.deobf("curse.maven:mmce-817377:6945422")
    compileOnly rfg.deobf ("curse.maven:baubles-227083:2518667")

}

tasks.named('reobfJar').configure {
    inputJar.set(tasks.named('shadowJar').flatMap({ it.archiveFile }))
}

tasks.shadowJar {
    archiveClassifier = 'uberdev'
    configurations = [ project.configurations.shade ]
}
